before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/imagesync/main.go
    binary: cede
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^*.sh:'