version: 2

before:
  hooks:
    - apt update
    - apt install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config -y
    - go mod download
builds:
  - main: ./cmd/imagesync/main.go
    binary: imagesync
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^*.sh:'
