name: "Imagesync CI"
on:
  push:
    branches: [ master ]

permissions: read-all

jobs:
  build-push-image:
    name: Build/Push imagesync image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/mqasimsarfraz/imagesync:latest

